import assert from 'node:assert/strict';

const origin = process.env.SMOKE_URL || 'http://localhost:3000';
const headers = process.env.VERCEL_AUTOMATION_BYPASS_SECRET ? { 'x-vercel-protection-bypass': process.env.VERCEL_AUTOMATION_BYPASS_SECRET } : {};
const request = (path, options = {}) => fetch(new URL(path, origin), { ...options, headers: { ...headers, ...options.headers }, signal: AbortSignal.timeout(30000) });
const home = await request('/');
assert.equal(home.status, 200, 'Home must load');
const html = await home.text();
assert.match(html, /Fine print\./, 'Landing content must be server rendered');
assert.match(html, /<meta name="description"/, 'SEO description missing');
assert.match(home.headers.get('content-security-policy') || '', /nonce-/, 'Nonce CSP missing');
const health = await request('/api/health');
assert.equal(health.status, 200);
assert.equal((await health.json()).status, 'ok');
const config = await request('/api/config');
assert.equal(config.status, 200);
assert.equal(typeof (await config.json()).ai.enabled, 'boolean');
const sample = await request('/samples/rental-agreement.txt');
assert.equal(sample.status, 200, 'Demo document must load');
const sampleText = await sample.text();
const analysis = await request('/api/analyze', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text: sampleText, options: { useAI: false } }) });
assert.equal(analysis.status, 200, 'Analysis API must work without an AI key');
assert.ok((await analysis.json()).clauses.length > 0);
const invalid = await request('/api/analyze', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' });
assert.equal(invalid.status, 400, 'Invalid input must be rejected');
const share = await request('/s/abcdefghijklmnopqrstuv');
assert.equal(share.status, 200);
assert.match(share.headers.get('x-robots-tag') || '', /noindex/);
assert.match(await share.text(), /noindex/);
assert.equal((await request('/robots.txt')).status, 200);
assert.equal((await request('/api/does-not-exist')).status, 404);
console.log('Smoke passed: SSR, SEO, CSP, API, validation, samples, private share indexing.');
